### ISSUE TITLE
website logo does not have a good resolution

### ISSUE THREAD

**Issue by christianealtayar** [EjazaliRezayi/Instafeed#10]
<img width="285" alt="instafeedLogo" src="https://user-images.githubusercontent.com/69988248/111242744-267aa700-85d6-11eb-9366-1d58916fc62a.PNG">

**Comment by DarenKaf** [comment]
Website logo image has a good resolution now. Issue can now be closed

**Comment by EjazaliRezayi** [comment]
Website logo has now a good resolution
