### ISSUE TITLE
As a user, I would like to have a user profile and be able to see other user's profile page

### ISSUE THREAD

**Issue by EjazaliRezayi** [EjazaliRezayi/Instafeed#16]
Description: As a user, I would like to have a user profile and be able to see other user's profile page

Steps:

User profiles front-end
User profiles should show previous posts of the user
User profiles should show the followers and who is following the user
User profiles should have a follow button

Priority: HIGH

Story points: 5 points

Acceptance testing:
1- User searches another user profile in the search bar.
2- User enters and will go to that user's user profile.
3- User can see previous posts, the followers and who the user is following.

**Comment by Kastor14** [comment]
After team discussion, we will implement the like button!
