### ISSUE TITLE
As a user, I want to like another user's picture

### ISSUE THREAD

**Issue by christianealtayar** [EjazaliRezayi/Instafeed#19]
Description: As a User, I would like to react on another user's picture without having to comment.

Steps: 
- UI for the like button 
- on click toggle between two icons
- Showing the names of people who liked the picture
- Showing the user that this picture is already liked

Priority : HIGH

Story points: 5 points

**Comment by Kastor14** [comment]
UI button works fine! Connecting it to database soon!

**Comment by EjazaliRezayi** [comment]
Like button works. The back-end implementation is done. It is merged to main.
