### ISSUE TITLE
As a User, I would like to login into my account

### ISSUE THREAD

**Issue by Kastor14** [EjazaliRezayi/Instafeed#3]
**Description:**

As a user, I want to have the ability to log into my account in Instafeed and access it. This includes navigating through my feed where I can keep up with the individuals I follow.

**Steps:** 

- Using React, the team must design an interactive page where the user is able to login using a valid username and password. This page must be submitted as a form for authentication. 
- Once submitted, the username is searched in the database. If found, an encrypted version of the password is compared with the stored encrypted version. 
- The logic must be implemented to process all the information from front to back end and further validate it. 
- If it matches what is stored in the database, the profile is updated with the latest login date time and the user is logged in. If it is unable to match, a message is displayed to the user indicating where the error took place (i.e wrong username or password).  

**Priority:** 
HIGH 

Story points: 5 points

Acceptance testing:
1- User sign up by clicking the sign up button and entering a valid email, username and password.
2- User sign in using the same email and password.

**Comment by EjazaliRezayi** [comment]
Users can now login, log out and sign in
